api:
  port: 8081

email:
  send_name: "我是测试员"
  email_QQ:
    host: smtp.qq.com
    port: 25
    username: 1169792186@qq.com
    auth_code: lffmruutpjpabadh

  email_163:
    host: smtp.163.com
    port: 25
    username: chenboyu131@163.com
    auth_code: RQNROMBGIZIAFZYO

sms:
  api_key: 14b1bbedae4ba4403778f551948e8026

